os: linux

language: python

python: "3.5"

dist: xenial

sudo: require

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - g++-
      - libboost-all-dev
      - libeigen3-dev
      - libglew-dev
      - libglfw-dev
      - freeglut3-dev
before_install:
  - sudo ln -s /usr/bin/gcc /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++- /usr/local/bin/g++
  - export CC=/usr/bin/gcc
  - export CXX=/usr/bin/g++-

install:
  - sudo apt-get install libqglviewer-dev qt4-dev-tools libopencv-dev

before_script:
  - cmake .

script:
  - make

after_success:
  - cp ${ROOT}/usr/lib/x86_64-linux-gnu/libQGLViewer.so $PWD/lib
  - zip -r -9 Release bin lib src

before_deploy:
  - git config --local user.name HaiDang2001VN
  - git config --local user.email danghailamhuynh@gmail.com
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key:
      secure: "Kco6ZHjEiO0OQp+4XZO+dcHX0n4uNihe2/TATl8MLRerbYNbgcteExWir3REtR3TOA0K228QzbApNw0azY8mEgcus0YWEGnOZctDOAtb5KWlSdCbVTcRAKiwfcR8SYE37aEaLNiap/ktSFf1v42qyvuLA6vAdxLzitOZZWKjijp3TcAahWB8v55f9luivbqA0zzSXTdr+nohKuuwHfCtqOvdyHlZeR29A3etQb2Q5iA/ouqucDSFdvB1W9qIlaXwb8O4jVji46370GMkTeVJpaqyomfpfsvy+iHBX+OnTzVKDEseD5Td87gWeVgUTMAq090CcG6DOQXi6Bs/KIMNgnKQBDFUHeHEudpDWETkN3oauXQ+s4m+PxQwZrkZHbmyBiuBko0n8ORsveAqRUa3bn9dkD1l9vYME4P5H16MUt3LojIHb0gXV4V0ScmmD+Ok4lEpwDlex8XbG6wgFR7gRul168GqHhn162RO6/UgMStCdYpTk391MkmUIXVjn+v12fjFEotRzpwDM5k/p/VADW3gCTGzb0r0C4Nld8zezhwguvErSpbolR44lLoqF+K5cCz2yY/KqF55aNecyLQ6ENn95FdGhbGYpfOt2kn7UTscPwQRG40LKnB4Ta4XG+UvDOQ8HltliibQzB9GyK8fThdO1qI8pbJht1hDE4m3o/M="
  file_glob: true
  file: "Release.zip"
  skip_cleanup: true
  overwrite: true
  on:
      repo: HaiDang2001VN/fastfusion
      all_branches: true
      tags: true
